sudo: false
jdk:
  - oraclejdk8
language: android
android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.0
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-license-[0-9a-f]{8}
script:
  ./gradlew build
after_failure:
  - cat app/build/outputs/lint-results-*.xml
